#!/usr/bin/env bash
# =============================================================================
# InvoDemo - One-command Docker setup
# Usage: ./run.sh <OPENAI_API_KEY>
# =============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

# ─── Check arguments ────────────────────────────────────────────────────────
if [ $# -lt 1 ] || [ -z "$1" ]; then
  echo "Usage: ./run.sh <OPENAI_API_KEY>"
  echo ""
  echo "Example:"
  echo "  ./run.sh sk-proj-abc123..."
  exit 1
fi

OPENAI_KEY="$1"

# ─── Check prerequisites ───────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install from https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || fail "Docker daemon is not running. Start Docker first."

# Check for docker compose (v2 plugin) or docker-compose (standalone)
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fail "Docker Compose is not installed."
fi

ok "Docker is ready ($COMPOSE)"

# ─── Navigate to script directory ──────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ─── Generate Supabase secrets ─────────────────────────────────────────────
info "Generating Supabase secrets..."

POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
JWT_SECRET=$(openssl rand -base64 64 | head -c 64)
SECRET_KEY_BASE=$(openssl rand -base64 48)
DASHBOARD_PASSWORD="password"

# Generate JWT tokens for Supabase anon and service_role
generate_jwt() {
  local secret="$1"
  local payload="$2"
  local header
  local body
  local sig
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -A | tr '+/' '-_' | tr -d '=')
  body=$(printf '%s' "$payload" | openssl base64 -A | tr '+/' '-_' | tr -d '=')
  sig=$(printf '%s.%s' "$header" "$body" | openssl dgst -sha256 -hmac "$secret" -binary | openssl base64 -A | tr '+/' '-_' | tr -d '=')
  printf '%s.%s.%s' "$header" "$body" "$sig"
}

ANON_KEY=$(generate_jwt "$JWT_SECRET" '{"role":"anon","iss":"supabase","iat":1700000000,"exp":1900000000}')
SERVICE_ROLE_KEY=$(generate_jwt "$JWT_SECRET" '{"role":"service_role","iss":"supabase","iat":1700000000,"exp":1900000000}')

ok "Secrets generated"

# ─── Write .env file ────────────────────────────────────────────────────────
info "Writing .env file..."

cat > .env <<ENVEOF
# Supabase Configuration (auto-generated by run.sh)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# URLs
SUPABASE_PUBLIC_URL=http://localhost:8000
API_EXTERNAL_URL=http://localhost:8000/auth/v1
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=

# Ports
KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443
POSTGRES_PORT=5432

# OpenAI
OPENAI_API_KEY=${OPENAI_KEY}
ENVEOF

ok ".env created"

# ─── Prepare volume directories ────────────────────────────────────────────
info "Preparing Docker volume directories..."

mkdir -p supabase/docker/volumes/api
mkdir -p supabase/docker/volumes/db/data
mkdir -p supabase/docker/volumes/storage

ok "Directories ready"

# ─── Start database first ──────────────────────────────────────────────────
info "Starting PostgreSQL database..."

$COMPOSE up -d db

info "Waiting for database to be healthy..."
for i in $(seq 1 40); do
  if $COMPOSE exec -T db pg_isready -U supabase_admin >/dev/null 2>&1; then
    ok "Database is ready"
    break
  fi
  if [ "$i" -eq 40 ]; then
    fail "Database did not become healthy in time. Check: $COMPOSE logs db"
  fi
  sleep 2
  printf '.'
done
echo ""

# ─── Fix DB user passwords ────────────────────────────────────────────────
info "Setting database user passwords..."

$COMPOSE exec -T db psql -U supabase_admin -d postgres -c "
ALTER USER authenticator WITH PASSWORD '${POSTGRES_PASSWORD}';
ALTER USER supabase_storage_admin WITH PASSWORD '${POSTGRES_PASSWORD}';
" 2>/dev/null

ok "Database users configured"

# ─── Run database migration ────────────────────────────────────────────────
info "Running database migration..."

$COMPOSE exec -T db psql -U supabase_admin -d postgres -f /dev/stdin < supabase/migrations/001_initial_schema.sql 2>/dev/null \
  || {
    warn "Direct stdin failed, copying migration file..."
    $COMPOSE cp supabase/migrations/001_initial_schema.sql "$( $COMPOSE ps -q db)":/tmp/001_initial_schema.sql
    $COMPOSE exec -T db psql -U supabase_admin -d postgres -f /tmp/001_initial_schema.sql
  }

ok "Database migration complete"

# ─── Start all services ────────────────────────────────────────────────────
info "Starting all services..."

$COMPOSE up -d

# ─── Wait for app to respond ───────────────────────────────────────────────
info "Waiting for the app to start (this may take a minute on first run)..."

for i in $(seq 1 60); do
  if curl -sf http://localhost:3000 >/dev/null 2>&1; then
    ok "App is ready!"
    break
  fi
  if [ "$i" -eq 60 ]; then
    warn "App may still be building. Check: $COMPOSE logs app"
  fi
  sleep 3
  printf '.'
done
echo ""

# ─── Create storage bucket (after storage service is running) ──────────────
info "Configuring storage..."

for i in $(seq 1 30); do
  if curl -sf http://localhost:5000/ >/dev/null 2>&1; then
    break
  fi
  if [ "$i" -eq 30 ]; then
    warn "Storage service not responding, skipping bucket setup"
    break
  fi
  sleep 2
done

# Grant storage schema permissions
$COMPOSE exec -T db psql -U supabase_admin -d postgres <<'SQL' 2>/dev/null || true
GRANT ALL ON SCHEMA storage TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA storage TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON SEQUENCES TO service_role;
GRANT USAGE ON SCHEMA storage TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA storage TO anon;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_buckets') THEN
    CREATE POLICY "service_role_all_buckets" ON storage.buckets
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_public_buckets') THEN
    CREATE POLICY "anon_read_public_buckets" ON storage.buckets
      FOR SELECT TO anon USING (public = true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service_role_all_objects') THEN
    CREATE POLICY "service_role_all_objects" ON storage.objects
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'anon_read_public_objects') THEN
    CREATE POLICY "anon_read_public_objects" ON storage.objects
      FOR SELECT TO anon USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated_insert_objects') THEN
    CREATE POLICY "authenticated_insert_objects" ON storage.objects
      FOR INSERT TO authenticated WITH CHECK (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'authenticated_read_objects') THEN
    CREATE POLICY "authenticated_read_objects" ON storage.objects
      FOR SELECT TO authenticated USING (true);
  END IF;
END $$;
SQL

# Create logos bucket via storage API
SERVICE_KEY_VAL=$(grep SERVICE_ROLE_KEY .env | cut -d= -f2)
for i in $(seq 1 10); do
  RESULT=$(curl -sf http://localhost:5000/bucket \
    -H "Authorization: Bearer ${SERVICE_KEY_VAL}" \
    -H "Content-Type: application/json" \
    -H "apikey: ${SERVICE_KEY_VAL}" \
    -d '{"id":"logos","name":"logos","public":true}' 2>&1) && break
  sleep 2
done

ok "Storage configured"

# ─── Print summary ─────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  InvoDemo is running!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "  App:              ${BLUE}http://localhost:3000${NC}"
echo -e "  Supabase Studio:  ${BLUE}http://localhost:3002${NC}"
echo -e "  Supabase API:     ${BLUE}http://localhost:8000${NC}"
echo ""
echo -e "  Studio login:     ${YELLOW}supabase / ${DASHBOARD_PASSWORD}${NC}"
echo ""
echo -e "  Next steps:"
echo -e "    1. Open ${BLUE}http://localhost:3000${NC}"
echo -e "    2. Click Sign Up and create an account"
echo -e "    3. Go to AI Generator and test with a prompt like:"
echo -e "       ${YELLOW}\"Invoice for John Doe. Items: Widget \$50 x3. Tax 10%. Due in 30 days.\"${NC}"
echo ""
echo -e "  Stop:    ${YELLOW}$COMPOSE down${NC}"
echo -e "  Reset:   ${YELLOW}$COMPOSE down -v && ./run.sh $OPENAI_KEY${NC}"
echo ""
